#[allow(dead_code)]
#[derive(Debug)]
pub enum Keyword {
    // SQL
    Absolute,
    Action,
    Add,
    All,
    Allocate,
    Alter,
    And,
    Any,
    Are,
    As,
    Asc,
    Assertion,
    At,
    Authorization,
    Avg,
    Begin,
    Between,
    Bit,
    BitLength,
    Both,
    By,
    Cascade,
    Cascaded,
    Case,
    Cast,
    Catalog,
    Char,
    Character,
    CharacterLength,
    CharLength,
    Check,
    Close,
    Coalesce,
    Collate,
    Collation,
    Column,
    Commit,
    Connect,
    Connection,
    Constraint,
    Constraints,
    Continue,
    Convert,
    Corresponding,
    Count,
    Create,
    Cross,
    Current,
    CurrentDate,
    CurrentTime,
    CurrentTimestamp,
    CurrentUser,
    Cursor,
    Date,
    Day,
    Deallocate,
    Decimal,
    Declare,
    Default,
    Deferrable,
    Deferred,
    Delete,
    Desc,
    Describe,
    Descriptor,
    Diagnostics,
    Disconnect,
    Distinct,
    Domain,
    Double,
    Drop,
    Else,
    End,
    EndExec,
    Escape,
    Except,
    Exception,
    Exec,
    Execute,
    Exists,
    External,
    Extract,
    False,
    Fetch,
    First,
    Float,
    For,
    Foreign,
    Found,
    From,
    Full,
    Get,
    Global,
    Go,
    Goto,
    Grant,
    Group,
    Having,
    Hour,
    Identity,
    Immediate,
    In,
    Indicator,
    Initially,
    Inner,
    Input,
    Insensitive,
    Insert,
    Int,
    Integer,
    Intersect,
    Interval,
    Into,
    Is,
    Isolation,
    Join,
    Key,
    Language,
    Last,
    Leading,
    Left,
    Level,
    Like,
    Local,
    Lower,
    Match,
    Max,
    Min,
    Minute,
    Module,
    Month,
    Names,
    National,
    Natural,
    NChar,
    Next,
    No,
    Not,
    Null,
    Nullif,
    Numeric,
    OctetLength,
    Of,
    On,
    Only,
    Open,
    Option,
    Or,
    Order,
    Outer,
    Output,
    Overlaps,
    Pad,
    Partial,
    Position,
    Precision,
    Prepare,
    Preserve,
    Primary,
    Prior,
    Privileges,
    Procedure,
    Public,
    Read,
    Real,
    References,
    Relative,
    Restrict,
    Revoke,
    Right,
    Rollback,
    Rows,
    Schema,
    Scroll,
    Second,
    Section,
    Select,
    Session,
    SessionUser,
    Set,
    Size,
    Smallint,
    Some,
    Space,
    Sql,
    Sqlcode,
    Sqlerror,
    Sqlstate,
    Substring,
    Sum,
    SystemUser,
    Table,
    Temporary,
    Then,
    Time,
    Timestamp,
    TimezoneHour,
    TimezoneMinute,
    To,
    Trailing,
    Transaction,
    Translate,
    Translation,
    Trim,
    True,
    Union,
    Unique,
    Unknown,
    Update,
    Upper,
    Usage,
    User,
    Using,
    Value,
    Values,
    VarChar,
    Varying,
    View,
    When,
    Whenever,
    Where,
    With,
    Work,
    Write,
    Year,
    Zone,
    // ADQL mathematical functions and operators
    Abs,
    Acos,
    Asin,
    Atan,
    Atan2,
    Ceiling,
    Cos,
    Degrees,
    Exp,
    Floor,
    Log,
    Log10,
    Mod,
    Pi,
    Power,
    Radians,
    Rand,
    Round,
    Sin,
    Sqrt,
    Tan,
    Top,
    Truncate,
    // ADQL geometric functions and operators
    Area,
    Box,
    Centroid,
    Circle,
    Contains,
    Coord1,
    Coord2,
    Coordsys,
    Distance,
    Intersects,
    Point,
    Polygon,
    Region,
}

impl Keyword {
    pub fn parse(string: &str) -> Option<Keyword> {
        match string {
            "ABSOLUTE" => Some(Keyword::Absolute),
            "ACTION" => Some(Keyword::Action),
            "ADD" => Some(Keyword::Add),
            "ALL" => Some(Keyword::All),
            "ALLOCATE" => Some(Keyword::Allocate),
            "ALTER" => Some(Keyword::Alter),
            "AND" => Some(Keyword::And),
            "ANY" => Some(Keyword::Any),
            "ARE" => Some(Keyword::Are),
            "AS" => Some(Keyword::As),
            "ASC" => Some(Keyword::Asc),
            "ASSERTION" => Some(Keyword::Assertion),
            "AT" => Some(Keyword::At),
            "AUTHORIZATION" => Some(Keyword::Authorization),
            "AVG" => Some(Keyword::Avg),
            "BEGIN" => Some(Keyword::Begin),
            "BETWEEN" => Some(Keyword::Between),
            "BIT" => Some(Keyword::Bit),
            "BIT_LENGTH" => Some(Keyword::BitLength),
            "BOTH" => Some(Keyword::Both),
            "BY" => Some(Keyword::By),
            "CASCADE" => Some(Keyword::Cascade),
            "CASCADED" => Some(Keyword::Cascaded),
            "CASE" => Some(Keyword::Case),
            "CAST" => Some(Keyword::Cast),
            "CATALOG" => Some(Keyword::Catalog),
            "CHAR" => Some(Keyword::Char),
            "CHARACTER" => Some(Keyword::Character),
            "CHARACTER_LENGTH" => Some(Keyword::CharacterLength),
            "CHAR_LENGTH" => Some(Keyword::CharLength),
            "CHECK" => Some(Keyword::Check),
            "CLOSE" => Some(Keyword::Close),
            "COALESCE" => Some(Keyword::Coalesce),
            "COLLATE" => Some(Keyword::Collate),
            "COLLATION" => Some(Keyword::Collation),
            "COLUMN" => Some(Keyword::Column),
            "COMMIT" => Some(Keyword::Commit),
            "CONNECT" => Some(Keyword::Connect),
            "CONNECTION" => Some(Keyword::Connection),
            "CONSTRAINT" => Some(Keyword::Constraint),
            "CONSTRAINTS" => Some(Keyword::Constraints),
            "CONTINUE" => Some(Keyword::Continue),
            "CONVERT" => Some(Keyword::Convert),
            "CORRESPONDING" => Some(Keyword::Corresponding),
            "COUNT" => Some(Keyword::Count),
            "CREATE" => Some(Keyword::Create),
            "CROSS" => Some(Keyword::Cross),
            "CURRENT" => Some(Keyword::Current),
            "CURRENT_DATE" => Some(Keyword::CurrentDate),
            "CURRENT_TIME" => Some(Keyword::CurrentTime),
            "CURRENT_TIMESTAMP" => Some(Keyword::CurrentTimestamp),
            "CURRENT_USER" => Some(Keyword::CurrentUser),
            "CURSOR" => Some(Keyword::Cursor),
            "DATE" => Some(Keyword::Date),
            "DAY" => Some(Keyword::Day),
            "DEALLOCATE" => Some(Keyword::Deallocate),
            "DECIMAL" => Some(Keyword::Decimal),
            "DECLARE" => Some(Keyword::Declare),
            "DEFAULT" => Some(Keyword::Default),
            "DEFERRABLE" => Some(Keyword::Deferrable),
            "DEFERRED" => Some(Keyword::Deferred),
            "DELETE" => Some(Keyword::Delete),
            "DESC" => Some(Keyword::Desc),
            "DESCRIBE" => Some(Keyword::Describe),
            "DESCRIPTOR" => Some(Keyword::Descriptor),
            "DIAGNOSTICS" => Some(Keyword::Diagnostics),
            "DISCONNECT" => Some(Keyword::Disconnect),
            "DISTINCT" => Some(Keyword::Distinct),
            "DOMAIN" => Some(Keyword::Domain),
            "DOUBLE" => Some(Keyword::Double),
            "DROP" => Some(Keyword::Drop),
            "ELSE" => Some(Keyword::Else),
            "END" => Some(Keyword::End),
            "END-EXEC" => Some(Keyword::EndExec),
            "ESCAPE" => Some(Keyword::Escape),
            "EXCEPT" => Some(Keyword::Except),
            "EXCEPTION" => Some(Keyword::Exception),
            "EXEC" => Some(Keyword::Exec),
            "EXECUTE" => Some(Keyword::Execute),
            "EXISTS" => Some(Keyword::Exists),
            "EXTERNAL" => Some(Keyword::External),
            "EXTRACT" => Some(Keyword::Extract),
            "FALSE" => Some(Keyword::False),
            "FETCH" => Some(Keyword::Fetch),
            "FIRST" => Some(Keyword::First),
            "FLOAT" => Some(Keyword::Float),
            "FOR" => Some(Keyword::For),
            "FOREIGN" => Some(Keyword::Foreign),
            "FOUND" => Some(Keyword::Found),
            "FROM" => Some(Keyword::From),
            "FULL" => Some(Keyword::Full),
            "GET" => Some(Keyword::Get),
            "GLOBAL" => Some(Keyword::Global),
            "GO" => Some(Keyword::Go),
            "GOTO" => Some(Keyword::Goto),
            "GRANT" => Some(Keyword::Grant),
            "GROUP" => Some(Keyword::Group),
            "HAVING" => Some(Keyword::Having),
            "HOUR" => Some(Keyword::Hour),
            "IDENTITY" => Some(Keyword::Identity),
            "IMMEDIATE" => Some(Keyword::Immediate),
            "IN" => Some(Keyword::In),
            "INDICATOR" => Some(Keyword::Indicator),
            "INITIALLY" => Some(Keyword::Initially),
            "INNER" => Some(Keyword::Inner),
            "INPUT" => Some(Keyword::Input),
            "INSENSITIVE" => Some(Keyword::Insensitive),
            "INSERT" => Some(Keyword::Insert),
            "INT" => Some(Keyword::Int),
            "INTEGER" => Some(Keyword::Integer),
            "INTERSECT" => Some(Keyword::Intersect),
            "INTERVAL" => Some(Keyword::Interval),
            "INTO" => Some(Keyword::Into),
            "IS" => Some(Keyword::Is),
            "ISOLATION" => Some(Keyword::Isolation),
            "JOIN" => Some(Keyword::Join),
            "KEY" => Some(Keyword::Key),
            "LANGUAGE" => Some(Keyword::Language),
            "LAST" => Some(Keyword::Last),
            "LEADING" => Some(Keyword::Leading),
            "LEFT" => Some(Keyword::Left),
            "LEVEL" => Some(Keyword::Level),
            "LIKE" => Some(Keyword::Like),
            "LOCAL" => Some(Keyword::Local),
            "LOWER" => Some(Keyword::Lower),
            "MATCH" => Some(Keyword::Match),
            "MAX" => Some(Keyword::Max),
            "MIN" => Some(Keyword::Min),
            "MINUTE" => Some(Keyword::Minute),
            "MODULE" => Some(Keyword::Module),
            "MONTH" => Some(Keyword::Month),
            "NAMES" => Some(Keyword::Names),
            "NATIONAL" => Some(Keyword::National),
            "NATURAL" => Some(Keyword::Natural),
            "NCHAR" => Some(Keyword::NChar),
            "NEXT" => Some(Keyword::Next),
            "NO" => Some(Keyword::No),
            "NOT" => Some(Keyword::Not),
            "NULL" => Some(Keyword::Null),
            "NULLIF" => Some(Keyword::Nullif),
            "NUMERIC" => Some(Keyword::Numeric),
            "OCTET_LENGTH" => Some(Keyword::OctetLength),
            "OF" => Some(Keyword::Of),
            "ON" => Some(Keyword::On),
            "ONLY" => Some(Keyword::Only),
            "OPEN" => Some(Keyword::Open),
            "OPTION" => Some(Keyword::Option),
            "OR" => Some(Keyword::Or),
            "ORDER" => Some(Keyword::Order),
            "OUTER" => Some(Keyword::Outer),
            "OUTPUT" => Some(Keyword::Output),
            "OVERLAPS" => Some(Keyword::Overlaps),
            "PAD" => Some(Keyword::Pad),
            "PARTIAL" => Some(Keyword::Partial),
            "POSITION" => Some(Keyword::Position),
            "PRECISION" => Some(Keyword::Precision),
            "PREPARE" => Some(Keyword::Prepare),
            "PRESERVE" => Some(Keyword::Preserve),
            "PRIMARY" => Some(Keyword::Primary),
            "PRIOR" => Some(Keyword::Prior),
            "PRIVILEGES" => Some(Keyword::Privileges),
            "PROCEDURE" => Some(Keyword::Procedure),
            "PUBLIC" => Some(Keyword::Public),
            "READ" => Some(Keyword::Read),
            "REAL" => Some(Keyword::Real),
            "REFERENCES" => Some(Keyword::References),
            "RELATIVE" => Some(Keyword::Relative),
            "RESTRICT" => Some(Keyword::Restrict),
            "REVOKE" => Some(Keyword::Revoke),
            "RIGHT" => Some(Keyword::Right),
            "ROLLBACK" => Some(Keyword::Rollback),
            "ROWS" => Some(Keyword::Rows),
            "SCHEMA" => Some(Keyword::Schema),
            "SCROLL" => Some(Keyword::Scroll),
            "SECOND" => Some(Keyword::Second),
            "SECTION" => Some(Keyword::Section),
            "SELECT" => Some(Keyword::Select),
            "SESSION" => Some(Keyword::Session),
            "SESSION_USER" => Some(Keyword::SessionUser),
            "SET" => Some(Keyword::Set),
            "SIZE" => Some(Keyword::Size),
            "SMALLINT" => Some(Keyword::Smallint),
            "SOME" => Some(Keyword::Some),
            "SPACE" => Some(Keyword::Space),
            "SQL" => Some(Keyword::Sql),
            "SQLCODE" => Some(Keyword::Sqlcode),
            "SQLERROR" => Some(Keyword::Sqlerror),
            "SQLSTATE" => Some(Keyword::Sqlstate),
            "SUBSTRING" => Some(Keyword::Substring),
            "SUM" => Some(Keyword::Sum),
            "SYSTEM_USER" => Some(Keyword::SystemUser),
            "TABLE" => Some(Keyword::Table),
            "TEMPORARY" => Some(Keyword::Temporary),
            "THEN" => Some(Keyword::Then),
            "TIME" => Some(Keyword::Time),
            "TIMESTAMP" => Some(Keyword::Timestamp),
            "TIMEZONE_HOUR" => Some(Keyword::TimezoneHour),
            "TIMEZONE_MINUTE" => Some(Keyword::TimezoneMinute),
            "TO" => Some(Keyword::To),
            "TRAILING" => Some(Keyword::Trailing),
            "TRANSACTION" => Some(Keyword::Transaction),
            "TRANSLATE" => Some(Keyword::Translate),
            "TRANSLATION" => Some(Keyword::Translation),
            "TRIM" => Some(Keyword::Trim),
            "TRUE" => Some(Keyword::True),
            "UNION" => Some(Keyword::Union),
            "UNIQUE" => Some(Keyword::Unique),
            "UNKNOWN" => Some(Keyword::Unknown),
            "UPDATE" => Some(Keyword::Update),
            "UPPER" => Some(Keyword::Upper),
            "USAGE" => Some(Keyword::Usage),
            "USER" => Some(Keyword::User),
            "USING" => Some(Keyword::Using),
            "VALUE" => Some(Keyword::Value),
            "VALUES" => Some(Keyword::Values),
            "VARCHAR" => Some(Keyword::VarChar),
            "VARYING" => Some(Keyword::Varying),
            "VIEW" => Some(Keyword::View),
            "WHEN" => Some(Keyword::When),
            "WHENEVER" => Some(Keyword::Whenever),
            "WHERE" => Some(Keyword::Where),
            "WITH" => Some(Keyword::With),
            "WORK" => Some(Keyword::Work),
            "WRITE" => Some(Keyword::Write),
            "YEAR" => Some(Keyword::Year),
            "ZONE" => Some(Keyword::Zone),
            _ => None,
        }
    }
}
